### ISSUE TITLE
Trying execute the data_selection script

### ISSUE THREAD

**Issue by baominhlt** [yaoxingcheng/TLM#12]
Hi yaoxingcheng,
Your work is so great.
I tried to execute your data_selection script with your example source and target data.
After finishing the execution, a selected data is created. It has 3 columns, these are "text","id" and "rank".
![image](https://user-images.githubusercontent.com/98018730/156294863-cdd8464f-b58f-43a4-be09-4cd07e3a01be.png)

However, when I access your released dataset, I found that your dataset has one different column (it is the "label" column).
![image](https://user-images.githubusercontent.com/98018730/156294829-e0d1d555-6bbd-4600-bc8a-6e03f0bc02f7.png)

I wonder if the "rank" column created by your original script is similar to the “label” column in your released datasets.
Sincerely,
baominhlt

**Comment by yaoxingcheng** [comment]
Hi~ Thanks for your attention. The "rank" column records the rank of an external data sample when it's retrieved from the source corpus by a task sample measured by BM25 score. For example, if query A retrieves A1, A2, A3, the similarity score between A and A1 is 0.9,  A and A2 is 0.8, A and A3 is 0.7, then the rank of A1 is 0, rank of A2 is 1 and the rank of A3 is 2. If a source sample is retrieved by multiple target samples, we will just take the minimum rank. 

Here, different from id which is unique for each retrieved sample, a rank value may be assigned to multiple retrieved samples. We hope rank could somehow characterize the distance between a retrieved sample and the task corpus and we can make some use of it in the future. Since we haven't used it now, so in our released dataset, the rank column is not included.

**Comment by baominhlt** [comment]
Thanks. I got it. Besides, how do you assign the label value for each row in your released datasets?

**Comment by yaoxingcheng** [comment]
What's shown in your screenshot from the released dataset is the task data instead of the external data retrieved by task data. The "label" column is just the annotated label in the task dataset.

**Comment by baominhlt** [comment]
Got it. Thanks yaoxingcheng. :3
